# Generated by Django 4.2.4 on 2023-10-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='note',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
