# Generated by Django 4.2.4 on 2023-10-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_education_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='note',
        ),
    ]
